// Testi dell'interfaccia del sito (in inglese) e categorie standard dei giochi.

export const T = {
  heroTitle: 'Play free browser games. <span>Instantly.</span>',
  heroText: 'No downloads, no installs and no sign-ups. Pick a game and start playing right in your browser.',
  gamesReady: n => (n ? `${n} ${n === 1 ? 'game' : 'games'} ready to play` : 'New games coming soon'),
  emptyTitle: 'No games yet',
  emptyText: 'New games are on the way. Check back soon!',
  searchPlaceholder: 'Search games, categories…',
  searchLabel: 'Search games',
  exploreGames: 'Explore games',
  countWords: ['game', 'games'],
  gamesCount: n => `${n} ${n === 1 ? 'game' : 'games'}`,
  noResults: 'No games found',
  tryAnother: 'Try another search or category.',
  filterLabel: 'Filter by category',
  all: 'All',
  badgeNew: 'New',
  badgeDraft: 'Draft',
  previewBadge: 'Preview',
  previewNotice: 'Preview site — built from the preview branches. Not indexed, no ads.',
  play: name => `Play ${name}`,
  home: 'Home',
  backHome: 'Back to home',
  loading: 'Loading game…',
  fullscreen: 'Fullscreen',
  exitFullscreen: 'Exit fullscreen',
  toggleTheme: 'Toggle theme',
  howToPlay: 'How to play',
  controls: 'Controls',
  moreGames: 'More games',
  pageTitle: name => `${name} — Play Free`,
  defaultDescription: name => `Play ${name} for free online — no download needed.`,
  privacy: 'Privacy & Cookies',
  contact: 'Contact',
  footerText: 'Free browser games.<br>No downloads. Just play.',
  rotate: 'Rotate your device for the best experience',
  by: 'By',
  updated: 'Updated',
  players: { SinglePlayer: '1 player', MultiPlayer: 'Multiplayer', Both: '1+ players' },
  notFoundText: "This page doesn't exist.",
  notFoundTitle: 'Page Not Found',
  player: name => `${name} game player`,
};

// Categorie standard. Una categoria diversa viene mostrata così com'è (con un avviso nel controllo).
export const CATEGORIES = ['Action', 'Arcade', 'Board', 'Card', 'Casual', 'Educational', 'Puzzle', 'Racing', 'Sports', 'Strategy', 'Other'];
